baseURL = "http://chunzhilun.cn/"
languageCode = "zh-cn"
title = "纯质论 ·PURE SUCHNESS CODEX"
theme = "hugo-theme-relearn"

# GitHub Pages 项目仓库常用设置
publishDir = "docs"
relativeURLs = false
canonifyURLs = false

defaultContentLanguage = "zh"
enableRobotsTXT = true

[params]
  author = "Zhou Luo (周罗)"
  keywords = [ "先验显现论","先验哲学","哲学第零问题","明性","自呈","纯质",
    "形而上学","现象学","非二元","认识论","折","界","曲率","息",
    "显现如何可能","自明","觉知","本体论","意识",
    "Luminosity","Self-presentation","Pure Suchness"]
  showVisitedLinks = true
  disableBreadcrumb = false
  disableLandingPageButton = false
  description  = "纯质论法典：以显现之先验可能为根基，设立明性、自呈与纯质之统一体，重铸形而上学的起点。"
  titleSeparator = "·"
   disablePathToLower = true

  [outputs]
  home = ["HTML","RSS","JSON"]
  images = ["/images/og-cover.png"]   # 放到 static/images/ 下
  
  

  [permalinks]
  posts = "/:sections/:slug/"

  [sitemap]
  priority   = 0.6
 defaultColor = "auto"


[menu]
  [[menu.main]]
    name = "Home 首页"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Volumes 法典"
    url = "/volumes/"
    weight = 2

    [[menu.main]]
    name = "introduction 导论"
    url = "/introduction/"
    weight = 3

  [[menu.main]]
    name = "Poems 明性之诗"
    url = "/poems/"
    weight = 4

  [[menu.main]]
    name = "Essays 论文"
    url = "/essays/"
    weight = 5

  [[menu.main]]
    name = "Meditations 明性实践与修行"
    url = "/meditations/"
    weight = 6

 [[menu.main]]
    name = "Notes 思想随笔"
    url = "/notes/"
    weight = 7

  [[menu.main]]
    name = "About 关于"
    url = "/about/"
    weight = 8

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
