baseURL = "https://fus12138.github.io/pure-suchness-codex/"
languageCode = "zh-cn"
title = "PURE SUCHNESS CODEX"
theme = "hugo-theme-relearn"

defaultContentLanguage = "zh"
hasCJKLanguage = true
summaryLength = 120
paginate = 10

[outputs]
  home = ["HTML","RSS"]   # 去掉 JSON，清掉警告

[params]
  disableLandingPageButton = false
  disableBreadcrumb = false
  disableNextPrev = false
  showVisitedLinks = true

[params.author]
  name = "Zhou Luo（周罗）"

[menu]
  [[menu.main]]
    name = "首页"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "三卷法典"
    url = "/volumes/"
    weight = 2

  [[menu.main]]
    name = "明性之诗"
    url = "/poems/"
    weight = 3

  [[menu.main]]
    name = "论文"
    url = "/essays/"
    weight = 4

  [[menu.main]]
    name = "明性实践与修行"
    url = "/meditations/"
    weight = 5

  [[menu.main]]
    name = "关于作者"
    url = "/about/"
    weight = 6